#!/usr/bin/env python3

import os
F = open('output', 'w')

title = os.system('figlet -f slant Lis Encription')
print()
print()

pet = input('Frase a encriptar: ')

longitud = len(pet)
# 4
count = int()
# 0
incount = int()
# 0
index = list()
# [3]
cordindex = dict()
# {'A': [0], 'r': [1], 'i': [2], 's': [3]}
processed = list()
# ['A', 'r', 'i', 's']
reps = dict()
# {'A': 1, 'r': 1, 'i': 1, 's': 1}

for rep in pet:
    if rep in processed:
        continue
    for i in pet:
        if i == rep:
            index.append(incount)
            count += 1
        incount += 1
    cordindex[rep] = index
    processed.append(rep)
    reps[rep] = count
    count = int()
    index = list()
    incount = int()

del index
F.write(str(longitud) + '(°-°)' + processed[0] + '%' + str(reps[processed[0]]) + '@')
for i in cordindex[processed[0]]:
    F.write(str(i) + '$')
F.write('^')
print(cordindex)
cordindex.pop(processed[0])
processed.pop(0)
for i in processed:
    F.write(processed[count] + '%' + str(reps[processed[count]]) + '@')
    for x in cordindex[processed[count]]:
        a = str(cordindex[processed[count]][incount])
        F.write(a + '$')
        incount += 1
    incount = int()
    F.write('^')
    count += 1
F.write('\n')
F.close()
